### ISSUE TITLE
Error on bundle install 

### ISSUE THREAD

**Issue by rodyoukai** [lbcclib/community_archive#1]
I get this when I try bundle Install:

> Git error: command `git reset --hard eb7df0b811fd26843e99b2e5e85b52a737d4e379` in
directory /home/rod/.rvm/gems/ruby-2.4.1/bundler/gems/syslogger-eb7df0b811fd has
failed.
If this error persists you could try removing the cache directory
'/home/rod/.rvm/gems/ruby-2.4.1/cache/bundler/git/syslogger-6ff85215ae9b346c0d5c3dddffc036451b90f894'

**Comment by sandbergja** [comment]
Hmmm... it's not working for me in 2.4.1 either.  Can you try it again using 2.4.2?

**Comment by rodyoukai** [comment]
I get the same result with ruby 2.4.2 & 2.5.0

**Comment by sandbergja** [comment]
Thanks for helping to troubleshoot this.  I think I found the problem.  Could you try installing this again with a fresh clone of the repository?

Thanks for your report!

**Comment by rodyoukai** [comment]
Hi @sandbergja, now is working, but I need comment gem clamav because fail in bundle install process

**Comment by sandbergja** [comment]
Thanks for confirming.  For testing/development purposes, you should be just fine without clamav.
